### ISSUE TITLE
Live documentation: mobile navigation error makes impossible to navigate the articles

### ISSUE THREAD

**Issue by lucasmrMM** [alkacon/opencms-documentation#16]
## Problem
On mobile device, it is currently impossible to navigate through the different live documentation articles. The main reason is the collapsible accordions in the mobile navigation right-side panel, which can't be uncollapsed.

### Link with an example of the error: 
[https://documentation.opencms.org/opencms-documentation/introduction/](https://documentation.opencms.org/opencms-documentation/introduction)

### Snapshot of the error: 
![image](https://user-images.githubusercontent.com/107122733/181118415-df2d8d50-c308-4cbc-a711-84138fb4f6f9.png)

### Tested on: 
  - Chrome Desktop, Version 103.0.5060.134 (Official Build) (64 bits)
  - Samsung Galaxy A03 Core, and Chrome Mobile Version 103.0.5060.71

## Expected behavior
Once I tap on the accordion arrows, the accordions should uncollapse. An example of working accordions can be found at: 
[https://documentation.opencms.org/central](https://documentation.opencms.org/central)

**Comment by alkacon-jGraf** [comment]
Thanks for your hint.
