### ISSUE TITLE
A JSP Template must be of type "Page Template" not just "JSP"

### ISSUE THREAD

**Issue by jobisoft** [alkacon/opencms-documentation#4]
At

http://documentation.opencms.org/opencms-documentation/creating-a-website/creating-a-template-jsp/

it is written:

 Afterwards go to /system/modules/my.template/templates/ and rename the index.html to main.jsp, then right click on main.jsp and choose the option: “Advanced” -> “Change type”, select the JSP radio button and confirm. With a click on the main.jsp a new browser window should open that shows the prototype correctly.

However, it should be a "Page Template" from the "Configurations" group (as the apollo template), otherwise the template will not be selectable in the Site management.

**Comment by dSeidel** [comment]
Thanks for the hint. I fixed it. It's fixed on GitHub and will be fixed in the Online documentation tomorrow.
