### ISSUE TITLE
Several file url lost

### ISSUE THREAD

**Issue by wtslh** [alkacon/opencms-documentation#9]
opencms-documentation/com.alkacon.opencms.documentation.content/resources/opencms-documentation/demos/dynamic-function-detail-pages/index.html,
in this page there should displays several file url,but lost.
![20170628132757](https://user-images.githubusercontent.com/2245560/27621795-d32f7c04-5c05-11e7-88f9-f7feaecd8706.png)

**Comment by dSeidel** [comment]
Thanks for the hint - and sorry for the slow reply. The next update on branch_11_0_x will include a fix.
